**Дан файл countries.csv**

В данном файле список стран и численность населения с 1952 по 2007 гг. с диапазоном в 5 лет 

1. Распаковать файл и данные сохранить в виде массивов 
2. Представить численность населения в виде миллиона человек 
3. Сделать массив населений двумерным из одномерного
4. Вычислить население всех стран в 2002 году
5. Посчитать прирост населения Алжира за каждые 5 лет с 1952 по 2007 гг. 

In [36]:
# Распакуем файл и добавим данные в массивы 

import csv
import numpy as np


f = open(r"C:\Users\VikhlyantsevAA\Desktop\15. Программирование на языке Python. Уровень 4. Анализ и визуализация данных\Материалы с курса\Датасеты\countries.csv")
numbers_of_lines = len(f.readlines()) - 1  # Общее кол-во строк без заголовка
f.seek(0)                                  # Возвращаем курсор в самое начало файла 


header = f.readline()  # Читаем заголовок
data = csv.reader(f)   # Записываем данные и присваиваем переменной data 


countries = np.empty(numbers_of_lines, dtype=(str, 15))    # Создаём пустой список стран 
years = np.empty(numbers_of_lines, dtype=np.uint64)        # Создаём пустой список годов 
populations = np.empty(numbers_of_lines, dtype=np.uint64)  # Создаём пустой список численности населения 


i = 0
for row in data:
    country = row[0]
    year = row[1]
    population = row[2]

    countries[i] = country
    years[i] = year
    populations[i] = population

    i += 1 

print(countries, years, populations)

['Afghanistan' 'Afghanistan' 'Afghanistan' ... 'Zimbabwe' 'Zimbabwe'
 'Zimbabwe'] [1952 1957 1962 ... 1997 2002 2007] [ 8425333  9240934 10267083 ... 11404948 11926563 12311143]


In [37]:
# Сохраним массивы в виде отдельных файлов:

np.savez('countries.npz', c=countries, y=years, p=populations)
countries_data = np.load('countries.npz')

In [38]:
# Присваиваем переменные массивам из файла countries.npz:

countries = countries_data['c']    # Присваиваем переменную странам из отдельного файла
years = countries_data['y']        # Присваиваем переменную годам из отдельного файла
populations = countries_data['p']  # Присваиваем переменную численности населения из отдельного файла

print(countries)
print(years)
print(populations)

['Afghanistan' 'Afghanistan' 'Afghanistan' ... 'Zimbabwe' 'Zimbabwe'
 'Zimbabwe']
[1952 1957 1962 ... 1997 2002 2007]
[ 8425333  9240934 10267083 ... 11404948 11926563 12311143]


In [39]:
# Численность населения в млн.чел:

population_millions = populations / 1_000_000
print(population_millions)

[ 8.425333  9.240934 10.267083 ... 11.404948 11.926563 12.311143]


In [40]:
# Двумерный массив:

# Так как у нас данные по 12-ти годам, то укажем неопределенной количество строк и 12 столбцов по годам 

population_matrix = populations.reshape(-1, 12)  
print(population_matrix)

print(f"Размер матрицы: {population_matrix.shape}")

[[ 8425333  9240934 10267083 ... 22227415 25268405 31889923]
 [ 1282697  1476505  1728137 ...  3428038  3508512  3600523]
 [ 9279525 10270856 11000948 ... 29072015 31287142 33333216]
 ...
 [ 4963829  5498090  6120081 ... 15826497 18701257 22211743]
 [ 2672000  3016000  3421000 ...  9417789 10595811 11746035]
 [ 3080907  3646340  4277736 ... 11404948 11926563 12311143]]
Размер матрицы: (142, 12)


In [48]:
# Численность населения за 2002 

year_2002_column_index = 10

population_2002 = population_matrix[ : , year_2002_column_index].sum()
print(f"Числонность населения за 2002 год: {population_2002} человек")

Числонность населения за 2002 год: 5886977579 человек


In [68]:
# Прирост населения Алжира 

algeria_idx_row = 2 # Индекс строки Алжира в массиве 

algeria_population = population_matrix[algeria_idx_row] # Население Алжира с 1952 по 2007 гг. с диапазоном в 5 лет 

# Первый вариант решения:
increases_algeria_popul = algeria_population[1:] - algeria_population[:-1]
print(increases_algeria_popul)


# Втрой вариант решения:
increases_algeria_popul_2 = np.diff(algeria_population)
print(increases_algeria_popul_2)

[ 991331  730092 1759551 2000288 2392017 2880949 3221203 3043417 2773642
 2215127 2046074]
[ 991331  730092 1759551 2000288 2392017 2880949 3221203 3043417 2773642
 2215127 2046074]
